/**
 * Build-time validator generation (no runtime `eval`).
 *
 * `@dome/protocol`'s registry compiles its Ajv validators when the module is imported, and Ajv's
 * runtime compiler uses `new Function`, which Manifest V3's extension CSP forbids (`unsafe-eval`
 * is never allowed for extension pages or the service worker). The extension therefore
 * precompiles the validators it needs from the SAME frozen schema files in
 * `shared/protocol/schemas/` with Ajv's standalone code generator. The output is plain JavaScript
 * with no code generation at runtime. `test/generated.test.ts` fails when the committed output is
 * out of date with the schemas, and `test/frames.test.ts` cross-checks the generated validators
 * against `schemas.validateBridgeFrame` from `@dome/protocol`.
 *
 *   pnpm gen:validators
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const here = dirname(fileURLToPath(import.meta.url));
export const SCHEMA_DIR = resolve(here, "../../shared/protocol/schemas");
export const OUTPUT_JS = resolve(here, "../src/generated/validators.js");
export const OUTPUT_DTS = resolve(here, "../src/generated/validators.d.ts");

const SCHEMA_DOCS = ["envelope", "command", "confirmation", "relay-frames", "bridge", "results", "entitlement", "rest"] as const;
const BASE = "https://dome.app/schemas/";
// Same `uri` format regex as shared/ts/src/registry.ts (the bridge schemas do not use formats, kept for parity).
const URI_FORMAT = /^(?:https?|wss?):\/\/[^\s/?#]+[^\s]*$/;

const EXPORTS: Record<string, string> = {
  extensionToAgent: `${BASE}bridge.schema.json#/$defs/extension_to_agent`,
  agentToExtension: `${BASE}bridge.schema.json#/$defs/agent_to_extension`,
  youtubeTab: `${BASE}relay-frames.schema.json#/$defs/youtube_tab`,
  tabsResult: `${BASE}results.schema.json#/$defs/tabs_result`,
  youtubeStateResult: `${BASE}results.schema.json#/$defs/youtube_state_result`,
};

export function generateValidatorsSource(): string {
  const ajv = new Ajv2020({
    strict: true,
    allErrors: false,
    allowUnionTypes: true,
    formats: { uri: URI_FORMAT },
    code: { source: true, esm: true, lines: true },
  });
  for (const name of SCHEMA_DOCS) {
    ajv.addSchema(JSON.parse(readFileSync(resolve(SCHEMA_DIR, `${name}.schema.json`), "utf8")) as object);
  }
  for (const ref of Object.values(EXPORTS)) {
    if (!ajv.getSchema(ref)) throw new Error(`schema ref not found: ${ref}`);
  }
  let code = standaloneCode(ajv, EXPORTS);
  // Ajv emits CommonJS requires for its runtime helpers even in ESM mode; turn them into imports.
  let n = 0;
  code = code.replace(/^const (\w+) = require\("(ajv\/dist\/runtime\/[\w/-]+)"\)\.default;$/gm, (_m, name: string, mod: string) => {
    n += 1;
    return `import __rt${n} from "${mod}.js";\nconst ${name} = __rt${n}.default ?? __rt${n};`;
  });
  if (/require\(/.test(code)) throw new Error("unexpected require() left in generated code");
  if (/new Function|\beval\(/.test(code)) throw new Error("generated code must not contain eval");
  const header = [
    "/* eslint-disable */",
    "// AUTO-GENERATED by scripts/gen-validators.ts from shared/protocol/schemas — do not edit.",
    "// Plain JavaScript validators (Ajv standalone); no code generation at runtime (MV3 CSP).",
    "",
  ].join("\n");
  return header + code.replace(/^"use strict";\n?/, "") + "\n";
}

export const DTS_SOURCE = `// AUTO-GENERATED by scripts/gen-validators.ts — do not edit.
export interface ValidationError {
  instancePath: string;
  schemaPath: string;
  keyword: string;
  params: Record<string, unknown>;
  message?: string;
}
export interface Validator {
  (value: unknown): boolean;
  errors?: ValidationError[] | null;
}
export const extensionToAgent: Validator;
export const agentToExtension: Validator;
export const youtubeTab: Validator;
export const tabsResult: Validator;
export const youtubeStateResult: Validator;
`;

function main(): void {
  writeFileSync(OUTPUT_JS, generateValidatorsSource());
  writeFileSync(OUTPUT_DTS, DTS_SOURCE);
  console.log(`wrote ${OUTPUT_JS}\nwrote ${OUTPUT_DTS}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
