"""Generate cross-language signing fixtures into shared/protocol/fixtures/es256-python.json.

Run: uv run python scripts/make_fixtures.py   (from shared/python)
The private key here is a TEST key committed on purpose; it has no other use.
"""

from __future__ import annotations

import json
from pathlib import Path

from dome_protocol import jwk_from_public_key, kid_from_jwk, private_key_from_pem, sign_payload
from dome_protocol.digest import challenge_digest, pairing_verification_code

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "protocol" / "fixtures"
TEST_KEY_PEM = (FIXTURE_DIR / "test-controller-key.pem").read_bytes()

PAYLOADS = [
    '{"type":"command","protocol_version":"1.0","command_id":"6f1c2d3e-4a5b-4c6d-8e7f-901234567890","account_id":"11111111-1111-4111-8111-111111111111","controller_id":"22222222-2222-4222-8222-222222222222","target_pc_id":"33333333-3333-4333-8333-333333333333","action":"youtube.next","params":{},"target":{"browser_instance_id":"bi_test0001","tab_id":42,"expected_video_id":"dQw4w9WgXcQ"},"issued_at":"2026-10-08T12:00:00.000Z","expires_at":"2026-10-08T12:00:30.000Z","nonce":"AAAAAAAAAAAAAAAAAAAAAA"}',
    '{"type":"command","protocol_version":"1.0","command_id":"7f1c2d3e-4a5b-4c6d-8e7f-901234567890","account_id":"11111111-1111-4111-8111-111111111111","controller_id":"22222222-2222-4222-8222-222222222222","target_pc_id":"33333333-3333-4333-8333-333333333333","action":"windows.set_volume","params":{"value":35},"target":null,"issued_at":"2026-10-08T12:00:00.000Z","expires_at":"2026-10-08T12:00:30.000Z","nonce":"AQEBAQEBAQEBAQEBAQEBAQ"}',
    '{"unicode":"ü→😀","nested":{"a":[1,2,3]}}',
]


def main() -> None:
    key = private_key_from_pem(TEST_KEY_PEM)
    jwk = jwk_from_public_key(key.public_key())
    kid = kid_from_jwk(jwk)
    cases = []
    for text in PAYLOADS:
        env = sign_payload(key, text)
        cases.append({"payload": text, "envelope": env.to_dict(), "expect": "valid"})
    # negative cases derived from the first valid envelope
    base = cases[0]["envelope"]
    tampered = dict(base, payload=base["payload"].replace('"tab_id":42', '"tab_id":43'))
    cases.append({"payload": tampered["payload"], "envelope": tampered, "expect": "SIGNATURE_INVALID"})
    bad_alg = dict(base, alg="none")
    cases.append({"payload": base["payload"], "envelope": bad_alg, "expect": "reject"})
    extra = dict(base, extra="x")
    cases.append({"payload": base["payload"], "envelope": extra, "expect": "MALFORMED_MESSAGE"})
    out = {
        "$comment": "Generated by shared/python/scripts/make_fixtures.py. TEST KEY ONLY.",
        "public_jwk": jwk,
        "kid": kid,
        "cases": cases,
        "digests": {
            "challenge_text": '{"challenge_id":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","command_id":"6f1c2d3e-4a5b-4c6d-8e7f-901234567890"}',
            "challenge_digest": challenge_digest('{"challenge_id":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","command_id":"6f1c2d3e-4a5b-4c6d-8e7f-901234567890"}'),
            "pairing_verification_code": pairing_verification_code(
                "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", "33333333-3333-4333-8333-333333333333", kid
            ),
        },
    }
    (FIXTURE_DIR / "es256-python.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", FIXTURE_DIR / "es256-python.json", "kid", kid)


if __name__ == "__main__":
    main()
