"""Generate cross-language signing fixtures into shared/protocol/fixtures/es256-python.json.

Run: uv run python scripts/make_fixtures.py   (from shared/python)
The private key here is a TEST key committed on purpose; it has no other use.
"""

from __future__ import annotations

import json
from pathlib import Path

from dome_protocol import jwk_from_public_key, kid_from_jwk, private_key_from_pem, sign_payload
from dome_protocol.digest import challenge_digest, command_digest, pairing_code_handle, pairing_verification_code

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "protocol" / "fixtures"
TEST_KEY_PEM = (FIXTURE_DIR / "test-controller-key.pem").read_bytes()

PAIRING_CODE = "7Q3K9-M2XVB-5HTC8-D4RNW"
PAIRING_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"
PC_ID = "33333333-3333-4333-8333-333333333333"

PAYLOADS = [
    '{"type":"command","protocol_version":"1.0","command_id":"6f1c2d3e-4a5b-4c6d-8e7f-901234567890","account_id":"11111111-1111-4111-8111-111111111111","controller_id":"22222222-2222-4222-8222-222222222222","target_pc_id":"33333333-3333-4333-8333-333333333333","action":"youtube.next","params":{},"target":{"browser_instance_id":"bi_test0001","tab_id":42,"tab_token":"dGFiLXRva2VuLTAxQUJDRE","expected_video_id":"dQw4w9WgXcQ"},"issued_at":"2026-10-08T12:00:00.000Z","expires_at":"2026-10-08T12:00:30.000Z","nonce":"AAAAAAAAAAAAAAAAAAAAAA"}',
    '{"type":"command","protocol_version":"1.0","command_id":"7f1c2d3e-4a5b-4c6d-8e7f-901234567890","account_id":"11111111-1111-4111-8111-111111111111","controller_id":"22222222-2222-4222-8222-222222222222","target_pc_id":"33333333-3333-4333-8333-333333333333","action":"windows.set_volume","params":{"value":35},"target":null,"issued_at":"2026-10-08T12:00:00.000Z","expires_at":"2026-10-08T12:00:30.000Z","nonce":"AQEBAQEBAQEBAQEBAQEBAQ"}',
    '{"unicode":"ü→😀","nested":{"a":[1,2,3]}}',
]

CHALLENGE_TEXT = (
    '{"challenge_id":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","command_id":"6f1c2d3e-4a5b-4c6d-8e7f-901234567890",'
    '"controller_id":"22222222-2222-4222-8222-222222222222","pc_id":"33333333-3333-4333-8333-333333333333",'
    '"action":"power.sleep","params":{"countdown_seconds":10},"target":null,'
    '"target_state_digest":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",'
    '"issued_at":"2026-10-08T12:00:00.000Z","expires_at":"2026-10-08T12:01:00.000Z",'
    '"display":{"pc_name":"Büro-PC","action_label":"Sleep","detail":"Sleep in 10 s — Bürö/ok"}}'
)


def main() -> None:
    key = private_key_from_pem(TEST_KEY_PEM)
    jwk = jwk_from_public_key(key.public_key())
    kid = kid_from_jwk(jwk)
    cases = []
    for text in PAYLOADS:
        env = sign_payload(key, text)
        cases.append({"payload": text, "envelope": env.to_dict(), "expect": "valid", "command_digest": command_digest(text)})
    base = cases[0]["envelope"]
    tampered = dict(base, payload=base["payload"].replace('"tab_id":42', '"tab_id":43'))
    cases.append({"payload": tampered["payload"], "envelope": tampered, "expect": "SIGNATURE_INVALID"})
    cases.append({"payload": base["payload"], "envelope": dict(base, alg="none"), "expect": "reject"})
    cases.append({"payload": base["payload"], "envelope": dict(base, extra="x"), "expect": "MALFORMED_MESSAGE"})
    out = {
        "$comment": "Generated by shared/python/scripts/make_fixtures.py. TEST KEY ONLY.",
        "public_jwk": jwk,
        "kid": kid,
        "cases": cases,
        "digests": {
            "challenge_text": CHALLENGE_TEXT,
            "challenge_digest": challenge_digest(CHALLENGE_TEXT),
            "pairing_code": PAIRING_CODE,
            "pairing_code_handle": pairing_code_handle(PAIRING_CODE),
            "pairing_id": PAIRING_ID,
            "pc_id": PC_ID,
            "pairing_verification_code": pairing_verification_code(PAIRING_CODE, PAIRING_ID, PC_ID, kid),
        },
    }
    (FIXTURE_DIR / "es256-python.json").write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", FIXTURE_DIR / "es256-python.json", "kid", kid)


if __name__ == "__main__":
    main()
