/**
 * Generate TypeScript types from the JSON Schemas in shared/protocol/schemas into src/generated.
 * Run: pnpm gen:types
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = resolve(here, "../../protocol/schemas");
const outDir = resolve(here, "../src/generated");
mkdirSync(outDir, { recursive: true });

const files: Array<[string, string]> = [
  ["envelope.schema.json", "envelope"],
  ["command.schema.json", "command"],
  ["confirmation.schema.json", "confirmation"],
  ["relay-frames.schema.json", "relayFrames"],
  ["bridge.schema.json", "bridge"],
  ["results.schema.json", "results"],
  ["entitlement.schema.json", "entitlement"],
  ["rest.schema.json", "rest"],
];

const header = "/* eslint-disable */\n// AUTO-GENERATED by scripts/gen-types.ts from shared/protocol/schemas — do not edit.\n\n";
const indexLines: string[] = ["// AUTO-GENERATED barrel — do not edit."];

for (const [file, name] of files) {
  const schema = JSON.parse(readFileSync(join(schemasDir, file), "utf8"));
  // json-schema-to-typescript resolves relative $refs against cwd.
  const ts = await compile(schema, name, {
    cwd: schemasDir,
    bannerComment: "",
    additionalProperties: false,
    strictIndexSignatures: true,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
  });
  writeFileSync(join(outDir, `${name}.ts`), header + ts);
  indexLines.push(`export type * as ${name} from "./${name}.ts";`);
  console.log("generated", name);
}
writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");
