/**
 * Digests and pairing helpers. Every function here has a byte-identical Python twin and is
 * covered by the cross-language fixtures.
 */
import { ProtocolError } from "./errors.ts";
import { b64url } from "./keys.ts";

// Crockford base32: no I, L, O, U; case-insensitive on input.
export const PAIRING_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
export const PAIRING_CODE_SYMBOLS = 20; // 100 bits of entropy; the code is a MAC key, not just a lookup handle
const CROCKFORD_ALIASES: Record<string, string> = { I: "1", L: "1", O: "0" };
const encoder = new TextEncoder();

export async function sha256B64url(data: Uint8Array | string): Promise<string> {
  const bytes = typeof data === "string" ? encoder.encode(data) : data;
  return b64url(await crypto.subtle.digest("SHA-256", bytes as BufferSource));
}

/** Digest of the challenge_text exactly as emitted by the PC and received by the controller. */
export async function challengeDigest(challengeText: string): Promise<string> {
  return sha256B64url(challengeText);
}

/** Digest of the exact signed payload bytes (duplicate detection in the PC journal). */
export async function commandDigest(payloadText: string): Promise<string> {
  return sha256B64url(payloadText);
}

// ----- pairing -----------------------------------------------------------------------------------

/** 20 Crockford symbols; the backend never sees this value. (Normally generated by the PC.) */
export function generatePairingCode(): string {
  const bytes = new Uint8Array(PAIRING_CODE_SYMBOLS);
  crypto.getRandomValues(bytes);
  let out = "";
  for (const b of bytes) out += PAIRING_ALPHABET[b % 32];
  return out;
}

/** Uppercase, drop separators/whitespace, map I/L→1 and O→0, validate length and alphabet. */
export function normalizePairingCode(text: unknown): string {
  if (typeof text !== "string") throw new ProtocolError("PAIRING_CODE_INVALID", "pairing code must be text");
  let cleaned = "";
  for (const ch of text.toUpperCase()) {
    if (" -_\t\r\n.".includes(ch)) continue;
    cleaned += CROCKFORD_ALIASES[ch] ?? ch;
  }
  if (cleaned.length !== PAIRING_CODE_SYMBOLS || [...cleaned].some((ch) => !PAIRING_ALPHABET.includes(ch))) {
    throw new ProtocolError("PAIRING_CODE_INVALID", "pairing code is not valid");
  }
  return cleaned;
}

export function formatPairingCode(code: string): string {
  const c = normalizePairingCode(code);
  return [c.slice(0, 5), c.slice(5, 10), c.slice(10, 15), c.slice(15, 20)].join("-");
}

/** Lookup handle sent to the backend by both devices: SHA-256 of the normalised code. */
export async function pairingCodeHandle(code: string): Promise<string> {
  return sha256B64url(`dome-pair-handle-v1|${normalizePairingCode(code)}`);
}

/**
 * 6-digit code shown on both devices during pairing: HMAC-SHA256 keyed by the out-of-band
 * pairing code over (pairing_id, pc_id, controller kid). The backend never holds the key.
 */
export async function pairingVerificationCode(code: string, pairingId: string, pcId: string, kid: string): Promise<string> {
  const key = await crypto.subtle.importKey("raw", encoder.encode(normalizePairingCode(code)), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const mac = new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(`dome-pair-verify-v1|${pairingId}|${pcId}|${kid}`)));
  let n = 0n;
  for (let i = 0; i < 8; i++) n = (n << 8n) | BigInt(mac[i] ?? 0);
  return (n % 1_000_000n).toString().padStart(6, "0");
}

export function randomNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return b64url(bytes);
}

export function randomUuid(): string {
  return crypto.randomUUID();
}
